-- MySQL Script generated by MySQL Workbench
-- Mon Jan 10 10:00:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pedreras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pedreras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pedreras` DEFAULT CHARACTER SET utf8 ;
USE `Pedreras` ;

-- -----------------------------------------------------
-- Table `Pedreras`.`Unities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedreras`.`Unities` (
  `idUnity` INT NOT NULL AUTO_INCREMENT,
  `entity` VARCHAR(70) NOT NULL,
  `adress` MEDIUMTEXT NOT NULL,
  `postal_code` INT NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  `quantity_unity` INT NOT NULL,
  `brand_unity` VARCHAR(50) NOT NULL,
  `tonne_capacity` INT NOT NULL,
  `number_plate` VARCHAR(10) NOT NULL,
  `tare_unity` VARCHAR(30) NOT NULL,
  `unity_type` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idUnity`),
  UNIQUE INDEX `idShipper_UNIQUE` (`idUnity` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedreras`.`Shipper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedreras`.`Shipper` (
  `idShipper` INT NOT NULL AUTO_INCREMENT,
  `entity` VARCHAR(70) NOT NULL,
  `adress` MEDIUMTEXT NOT NULL,
  `postal_code` INT NOT NULL,
  `municipality` VARCHAR(20) NOT NULL,
  `quantity_unity` FLOAT NOT NULL,
  `brand_unity` VARCHAR(50) NOT NULL,
  `tonne_capacity` INT NOT NULL,
  `number_plate` VARCHAR(10) NOT NULL,
  `tare_unity` VARCHAR(30) NOT NULL,
  `unity_type` VARCHAR(1) NOT NULL,
  `Unities_idUnity` INT NOT NULL,
  PRIMARY KEY (`idShipper`),
  UNIQUE INDEX `idShipper_UNIQUE` (`idShipper` ASC),
  INDEX `fk_Shipper_Unities_idx` (`Unities_idUnity` ASC),
  CONSTRAINT `fk_Shipper_Unities`
    FOREIGN KEY (`Unities_idUnity`)
    REFERENCES `Pedreras`.`Unities` (`idUnity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedreras`.`Quarries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedreras`.`Quarries` (
  `idQuarries` INT NOT NULL AUTO_INCREMENT,
  `entity` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `adreess` MEDIUMTEXT NOT NULL,
  `postal_code` INT NOT NULL,
  `municipality` VARCHAR(20) NOT NULL,
  `RFC` VARCHAR(13) NOT NULL,
  `time_atention` VARCHAR(50) NOT NULL,
  `products` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idQuarries`),
  UNIQUE INDEX `idQuarries_UNIQUE` (`idQuarries` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pedreras`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pedreras`.`Clients` (
  `idQuarries` INT NOT NULL AUTO_INCREMENT,
  `entity` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(13) NOT NULL,
  `email` VARCHAR(45) NULL,
  `adreess` MEDIUMTEXT NOT NULL,
  `postal_code` INT NOT NULL,
  `municipality` VARCHAR(20) NOT NULL,
  `RFC` VARCHAR(13) NOT NULL,
  `time_atention` VARCHAR(50) NOT NULL,
  `Projects` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idQuarries`),
  UNIQUE INDEX `idQuarries_UNIQUE` (`idQuarries` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
